## Homework

#### Q1. Pandas version

In [7]:
import pandas as pd
import numpy as np
import urllib.request


In [3]:
pd.__version__


'3.0.5'

In [5]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
urllib.request.urlretrieve(url, "car_fuel_efficiency.csv")

('car_fuel_efficiency.csv', <http.client.HTTPMessage at 0x1f549758190>)

In [6]:
df = pd.read_csv("car_fuel_efficiency.csv")

#### Q2. Records count

In [9]:
df.shape[0]

9704

#### Q3. Fuel types

In [12]:
df['fuel_type'].nunique()

2

#### Q4. Missing values

In [21]:
int((df.isnull().sum() > 0).sum())

4

#### Q5. Max fuel efficiency


In [26]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

#### Q6. Median value of horsepower


In [27]:
df['horsepower'].median()

np.float64(149.0)

In [28]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [30]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [31]:
df['horsepower'].median()

np.float64(152.0)

#### Q7. Sum of weights

In [36]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']][:7].values

In [37]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [39]:
X.shape

(7, 2)

In [40]:
X_T = X.T

In [41]:
X_T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [43]:
XTX = X_T.dot(X)

In [44]:
np.linalg.inv(XTX)

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [45]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [47]:
np.linalg.inv(XTX).dot(X_T).dot(y).sum()

np.float64(0.5187709081074016)