## Homework

#### Q1. Pandas version

In [1]:
import pandas as pd
import numpy as np
import urllib.request


In [2]:
pd.__version__

'3.0.5'

In [3]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
urllib.request.urlretrieve(url, "car_fuel_efficiency.csv")

('car_fuel_efficiency.csv', <http.client.HTTPMessage at 0x1c382762210>)

In [4]:
df = pd.read_csv("car_fuel_efficiency.csv")

#### Q2. Records count

In [5]:
df.shape[0]

10000

#### Q3. Fuel types

In [6]:
df['fuel_type'].nunique()

3

#### Q4. Missing values

In [7]:
int((df.isnull().sum() > 0).sum())

2

#### Q5. Max fuel efficiency


In [8]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

#### Q6. Median value of horsepower


In [9]:
df['horsepower'].median()

np.float64(254.0)

In [10]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [11]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [12]:
df['horsepower'].median()

np.float64(252.0)

#### Q7. Sum of weights

In [13]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']][:7].values

In [14]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [15]:
X.shape

(7, 2)

In [16]:
X_T = X.T

In [17]:
X_T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [18]:
XTX = X_T.dot(X)

In [19]:
np.linalg.inv(XTX)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [21]:
np.linalg.inv(XTX).dot(X_T).dot(y).sum()

np.float64(0.36919696904925486)