In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'd:\\Projects\\ML-Zoomcamp\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>

### Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
a = np.array([1, 2 ,5, 7])

In [7]:
a[2]

np.int64(5)

In [8]:
a[2] = 14

In [9]:
a

array([ 1,  2, 14,  7])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

### Multi Dimensional arrays

In [17]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [22]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
n[0, 1] = 20

In [24]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [25]:
n[0]

array([ 1, 20,  3])

In [26]:
n[2] = [1, 5 , 9]

In [27]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  5,  9]])

In [28]:
n[:, 1]

array([20,  5,  5])

In [29]:
n[:, 1] = [10, 20, 30]

In [30]:
n

array([[ 1, 10,  3],
       [ 4, 20,  6],
       [ 1, 30,  9]])

### Randomly generated arrays

In [32]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [33]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [34]:
np.random.seed(2)
100 * np.random.randn(5, 2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [35]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

### Element-wise operations

In [36]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a + 1

array([1, 2, 3, 4, 5])

In [38]:
a * 8

array([ 0,  8, 16, 24, 32])

In [39]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [42]:
b = (10 + (a * 2)) ** 3

In [43]:
a + b

array([1000, 1729, 2746, 4099, 5836])

In [44]:
a / b

array([0.        , 0.0005787 , 0.00072886, 0.00073242, 0.00068587])

### Comparisons operations

In [45]:
a > b

array([False, False, False, False, False])

In [46]:
a >= 3

array([False, False, False,  True,  True])

In [47]:
b 

array([1000, 1728, 2744, 4096, 5832])

In [48]:
b > 2000

array([False, False,  True,  True,  True])

In [49]:
a > b

array([False, False, False, False, False])

In [50]:
b = b / 1000

In [54]:
b = b - 1

In [55]:
a > b

array([False,  True,  True, False, False])

In [76]:
b[a > b]

array([0.728, 1.744])

In [73]:
a

array([0, 1, 2, 3, 4])

### Summarizing operations

In [60]:
a.min()

np.int64(0)

In [61]:
a.mean()

np.float64(2.0)

In [62]:
a.std()

np.float64(1.4142135623730951)

In [63]:
n.sum()

np.int64(84)

In [64]:
n.min()

np.int64(1)

In [77]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [87]:
n = np.eye(5)

In [86]:
a.dot(n)

array([0., 1., 2., 3., 4.])

In [90]:
def vector_vector_dot(u,v):
    assert u.shape == v.shape, "Vectors must be the same shape"

    result = np.zeros(u.shape[0])
    for i in range(u.shape[0]):
        result[i] = u[i] * v[i]
    return result


In [91]:
u = np.array([1, 2, 3, 4])
v = np.array([4, 3, 2, 1])

uv = vector_vector_dot(u, v)
print(uv)

[4. 6. 6. 4.]


In [92]:
def matrix_vector_dot(U, v):
    assert U.shape[1] == v.shape[0], "Matrix columns must match vector size"

    result = np.zeros(U.shape[0])
    for i in range(U.shape[0]):
        result[i] = vector_vector_dot(U[i, :], v)
    return result

In [94]:
U = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
v = np.array([1, 2, 3])
result = matrix_vector_dot(U, v)

In [95]:
print(result)
print(np.dot(U, v))

[14. 32. 50.]
[14 32 50]


In [96]:
def matrix_matrix_dot(U, V):
    assert U.shape[1] == V.shape[0], "Incompatible shapes for matrix multiplication"

    result = np.zeros((U.shape[0], V.shape[1]))
    for i in range(V.shape[1]):
        matrix_vector_result = matrix_vector_dot(U, V[:, i])
        result[:, i] = matrix_vector_result
    return result

In [97]:
U = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

V = np.array([
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

result = matrix_matrix_dot(U, V)
print(result)

print(np.dot(U, V))

[[ 48.  54.  60.]
 [111. 126. 141.]
 [174. 198. 222.]]
[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


In [99]:
assert np.all(matrix_matrix_dot(U, V) == np.dot(U, V))

LinAlgError: Singular matrix

In [105]:
U = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 10]
])


In [106]:
U_inv = np.linalg.inv(U)
I = np.eye(U.shape[0])
print(U.dot(U_inv))

[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]
